#!/usr/bin/env bash
# script install nginx web server

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo service nginx start
sudo touch /var/www/html/index.html && sudo chmod 777 /var/www/html/index.html
echo "Hello World!" | sudo tee /var/www/html/index.html
