#!/usr/bin/env bash
#script that change redirct me

sudo apt-get -y update
sudo apt-get -y install nginx
sudo service nginx start
url="\trewrite ^/(.*)$ http://www.youtube.com permanent;"
sudo sed -i "/server_name _;/a $url" /etc/nginx/sites-available/default
sudo service nginx restart
sudo service nginx reload
