#!/usr/bin/env bash
# script to instal HAproxy and configure it

sudo apt-get -y update
sudo apt-get -y install haproxy
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
sudo mv /etc/haproxy/haproxy.cfg{,.original}
sudo touch /etc/haproxy/haproxy.cfg
text=$(cat << 'END HEREDOC'
global
	log 127.0.0.1 local0 notice
	maxconn 2000
	user haproxy
	group haproxy
defaults
	log     global
	mode    http
	option  httplog
	option  dontlognull
	retries 3
	option redispatch
	timeout connect  5000
	timeout client  10000
	timeout server  10000
listen myservers
	bind 0.0.0.0:80
	mode http
	stats enable
	stats uri /haproxy?stats
	balance roundrobin
	option httpclose
	option forwardfor
	server 244274-web-01 100.25.103.38:80 check
	server 244274-web-02 54.237.107.99:80 check
END HEREDOC
)
echo -e "$text" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy start
