#!/usr/bin/env bash
# script that manage signals term, int , quit
echo $$ > /var/run/myscript.pid
i=1
while [ $i -gt 0 ]
do
	echo "To infinity and beyond"
	trap 'echo "Y U no love me?!"' INT
	trap 'echo "I hate the kill command"; rm /var/run/myscript.pid; exit 0' TERM
	trap 'rm /var/run/myscript.pid; exit 0' QUIT
done
