#!/usr/bin/env bash
# script print story from file
while read -r line
do
	usrn=$(echo "$line" | cut -d ":" -f 1)
	grp=$(echo "$line" | cut -d ":" -f 4)
	home=$(echo "$line" | cut -d ":" -f 6)
	com=$(echo "$line" | cut -d ":" -f 7)
	id=$(echo "$line" | cut -d ":" -f 3)
	pass=$(echo "$line" | cut -d ":" -f 2)
	info=$(echo "$line" | cut -d ":" -f 5)
	echo "The user $usrn is part of the $grp gang, lives in $home and rides $com. $id's place is protected by the passcode $pass, more info about the user here: $info"
done < /etc/passwd
