#!/usr/bin/env bash
# script that print "best school" 10 times and in nine time print hi instead
i=0
while [ $i -lt 10 ]
do
	if [ $i = 8 ]
	then
		echo "Hi"
	else
		echo "Best School"
	fi
	i=$((i+1))
done
