#!/usr/bin/env bash
# script run nginx user

sudo chown nginx /etc/nginx/nginx.conf
sudo chmod u+r /etc/nginx/nginx.conf
sudo sed -i "s/80/8080/g" /etc/nginx/sites-available/default
sudo -u nginx service nginx restart
